### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by lfarah** [abdullahselek/Merhaba#1]
Hey, your library is really interesting.

The only problem I found was the ```README.md```, which lacks information.
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize.
If you want, I can help you to do it.

What are your thoughts?

**Comment by lfarah** [comment]
Please fix this before I can [merge your PR](https://github.com/vsouza/awesome-ios/pull/1404)

**Comment by abdullahselek** [comment]
Hey, I updated the README file. Could you please check again?

**Comment by lfarah** [comment]
Thanks!
