### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by mdpp** [abdullahselek/Merhaba#2]
Hi, trying to compile it for the first time and got the following error:

Merhaba/Sample/iOS Sample/iOS Sample/ViewController.m:31:35: No visible @interface for 'MRBServer' declares the selector 'start'

I didn't modify the source code at all. Any idea?

**Comment by abdullahselek** [comment]
Hi @mdpp you can checkout the new changes samples should be working now. Just a small note before building the samples apps build related Merhaba target ;)

**Comment by mdpp** [comment]
It complies now! Thanks.
